- name: Build maintenance backend (local - no pull)
  hosts: "node-ibm"
  become: no
  tasks:
    - name: run deployment script
      command: ./build-backend-local.sh
      args:
        chdir: /home/gis/www/gce-maintenance-new
      register: results
    - debug:
        var: results.stdout

