- name: create a file test
  hosts: "{{ servers }}"
  become: no
  tasks:
    - name: run deployment script
      command: test.sh
      args:
      chdir: /home/gis/www/gce-maintenance-new/
      register: results
    - debug:
        var: results.stdout
