- name: create a file test
  hosts: "{{ servers }}"
  become: no
  tasks:
    - name: run deployment script
      command:
        cmd: test.sh
        chdir: /home/gis/www/gce-maintenance-new/
      register: results
    - debug:
        var: results.stdout

