- name: create a file test
  hosts: "{{ servers }}"
  become: no
  tasks:
    - name: run deployment script
      command: /home/gis/www/gce-maintenance-new/test.sh
      register: results
    - debug:
        var: results.stdout
