- name: create a file test
  hosts: "{{ servers }}"
  become: no
  tasks:
    - name: run deployment script
    - script: test.sh
      register: results
      args:
        chdir: /home/gis/www/gce-maintenance-new/
    - debug:
        var: results.stdout
