- name: create a file test
  hosts: "servers"
  become: no
  tasks:
    - name: run deployment script
      command:
        cmd: ls
        chdir: ~/www/gce-maintenance-new
      register: results
    - debug:
        var: results.stdout

