- name: Build maintenance backend (local - no pull)
  hosts: "node-ibm"
  become: no
  tasks:
    - name: run deployment script
      command: ./pull.sh {{ rsa_passphrase }}
      args:
        chdir: /home/gis/www/gce-maintenance-new
      register: results
    - debug:
        var: results.stdout