- name: Build maintenance backend (local - no pull)
  hosts: "node-ibm"
  become: no
  tasks:
    - name: run deployment script
      command: ./pull.sh
      args:
        chdir: /home/gis/www/gce-maintenance-new
        stdin: "{{ rsa_passphrase }}\n"
      register: results
    - debug:
        var: results.stdout